let games = [
    ["Doom","https://nueot-437a9.web.app/games/doom.html"],
    ["FF 1&2 Advance","https://nueot-437a9.web.app/games/ff12.html"],
    ["FFV Advance","https://nueot-437a9.web.app/games/ffv.html"],
    ["Leafgreen","https://nueot-437a9.web.app/games/lg.html"],
    ["FFIV Advance","https://nueot-437a9.web.app/games/ffivadv.html"],
    ["Mario Kart Super Circut","https://nueot-437a9.web.app/games/mksc.html"],
    ["Emerald","https://nueot-437a9.web.app/games/emerald.html"],
    ["Minish Cap","https://nueot-437a9.web.app/games/mc.html"],
    ["Spyro","https://nueot-437a9.web.app/games/spyro.html"],
    ["FFVI Adv","https://nueot-437a9.web.app/games/ffvien.html"],
    ["Kirby Nightmare","https://nueot-437a9.web.app/games/nightmare.html"],
    ["FFIV","https://nueot-437a9.web.app/games/ffiv-snes.html"],
    ["FFVI (3)","https://nueot-437a9.web.app/games/ffvi-snes.html"],
    ["Link to the Past","https://nueot-437a9.web.app/games/lttp.html"],
    ["Super Mario Kart","https://nueot-437a9.web.app/games/smk.html"],
    ["Yoshi's Island","https://nueot-437a9.web.app/games/yo.html"],
    ["Yoshi's Island ROM Hack","https://nueot-437a9.web.app/games/yoshi.html"],
    ["Mario World","https://nueot-437a9.web.app/games/smw.html"],
    ["Earthbound","https://nueot-437a9.web.app/games/eb.html"],
    ["Street Fighter 2","https://nueot-437a9.web.app/games/sf2t.html"],
    ["Donkey Kong Country","https://nueot-437a9.web.app/games/dkc.html"],
    ["Super Meteroid","https://nueot-437a9.web.app/games/sm.html"],
    ["F-Zero","https://nueot-437a9.web.app/games/f0.html"],
    ["Star Fox","https://nueot-437a9.web.app/games/sf.html"],
    ["Kirby Superstar","https://nueot-437a9.web.app/games/superkirby.html"],
    ["Pilotwings","https://nueot-437a9.web.app/games/pilot.html"],
    ["Secret of Mana","https://nueot-437a9.web.app/games/secretom.html"],
    ["Super Ghouls and Ghosts","https://nueot-437a9.web.app/games/ghouls.html"],
    ["Megaman X","https://nueot-437a9.web.app/games/megamanx.html"],
    ["Contra 3","https://nueot-437a9.web.app/games/contra3.html"],
    ["Kirby Dreamland","https://nueot-437a9.web.app/games/dreamland.html"],
    ["Super Mario RPG","https://nueot-437a9.web.app/games/mariorpg.html"],
    ["Terranigma","https://nueot-437a9.web.app/games/terranigma.html"],
    ["Super Mario World","https://nueot-437a9.web.app/games/smw.html"],
    ["Mario Kart 64","http://classicmc-studios.github.io/NeptunJS/mk64.html"],
    ["Super Smash Bros 64","https://nueot-437a9.web.app/games/ssb.html"],
    ["Paper Mario","https://nueot-437a9.web.app/games/pm.html"],
    ["Super Mario 64","https://nueot-437a9.web.app/games/sm64.html"],
    ["Mario Tennis 64","http://classicmc-studios.github.io/NeptunJS/mt.html"],
    ["Star Fox 64","https://nueot-437a9.web.app/games/sf64.html"],
    ["Donkey Kong 64","https://nueot-437a9.web.app/games/dk64.html"],
    ["Harvest Moon 64","https://nueot-437a9.web.app/games/hm64.html"],
    ["Ocarina of Time","http://classicmc-studios.github.io/NeptunJS/tlozoc.html"],
    ["Banjo Kazooie","https://nueot-437a9.web.app/games/bk64.html"],
    ["Quake 64","https://nueot-437a9.web.app/games/quake64.html"],
    ["Kirby 64","https://nueot-437a9.web.app/games/kirby64.html"],
    ["Riddle School 1","https://guyotjs.github.io/flash/games/rs1.html"],
    ["Riddle School 2","https://guyotjs.github.io/flash/games/rs1.html"],
    ["Riddle School 3","https://guyotjs.github.io/flash/games/rs3.html"],
    ["Fancy Pants Adventure","https://guyotjs.github.io/flash/games/fpa.html"],
    ["Fancy Pants Adventure 2","https://guyotjs.github.io/flash/games/fpa2.html"],
    ["Fancy Pants Adventure 3","https://guyotjs.github.io/flash/games/fpa3.html"],
    ["Breaking the Bank","https://guyotjs.github.io/flash/games/btb.html"],
    ["Escaping the Prison","https://guyotjs.github.io/flash/games/etp.html"],
    ["Stealing the Diamond","https://guyotjs.github.io/flash/games/std.html"],
    ["Bloxors","https://guyotjs.github.io/flash/games/b.html"],
    ["Duck Life Treasure Hunt","https://guyotjs.github.io/flash/games/dlth.html"],
    ["Fleeing the Complex","https://guyotjs.github.io/flash/games/ftc.html"],
    ["I'm Outta Here","https://guyotjs.github.io/flash/games/ioh.html"],
    ["Infiltrating the Airship","https://guyotjs.github.io/flash/games/ita.html"],
    ["Line Rider","https://guyotjs.github.io/flash/games/lr2.html"],
    ["Super Mario Flash 2","https://guyotjs.github.io/flash/games/smf2.html"],
    ["Super Smash Flash","https://guyotjs.github.io/flash/games/ssf.html"],
    ["The Binding of Issac","https://guyotjs.github.io/flash/games/tboi.html"],
    ["The World's Hardest Game","https://guyotjs.github.io/flash/games/twhg.html"],
]
